---
title: "Kursinis"
author: "Kornelijus Samsonas, Linas Šyvis"
date: "30 September 2016"
output: html_document
---

```{r}

library(readxl)
rawdata<-read_excel('tidy2015.xls')
```

Tikrinsime hipotezę ar Vilniaus mieste eismo įvykių kaltininkai dažniau yra Vyrai nei moterys.

H0= V sk. = 

```{r}
Vilniusm <- rawdata[rawdata[,1] == "Vilniaus m. sav.",]
Kaunasm <- rawdata[rawdata[,1] == "Kauno m. sav.",]
Siauliaim <- rawdata[rawdata[,1] == "siauliu m. sav.",]
Klaipedam <- rawdata[rawdata[,1] == "Klaipedos m. sav.",]
Panevezysm <- rawdata[rawdata[,1] == "Panevezio m. sav.",]

```


### Kaltininku procentas miestuose (Vyrai/Moterys)

Kaltininkų procentas Vilniaus mieste.

```{r}
vyruskV<-sum(na.omit(as.numeric(Vilniusm[,19]=="Vyras")))
moteruskV<-sum(na.omit(as.numeric(Vilniusm[,19]=="Moteris")))
visoV<-(vyruskV+moteruskV)
vyruprocV=vyruskV/visoV*100
moteruprocV=moteruskV/visoV*100
```

Kaltininkų procentas Kauno mieste.

```{r}
vyruskK<-sum(na.omit(as.numeric(Kaunasm[,19]=="Vyras")))
moteruskK<-sum(na.omit(as.numeric(Kaunasm[,19]=="Moteris")))
visoK<-(vyruskK+moteruskK)
vyruprocK=vyruskK/visoK*100
moteruprocK=moteruskK/visoK*100
```

Kaltininkų procentas Siauliu mieste.

```{r}
vyruskS<-sum(na.omit(as.numeric(Siauliaim[,19]=="Vyras")))
moteruskS<-sum(na.omit(as.numeric(Siauliaim[,19]=="Moteris")))
visoS<-(vyruskS+moteruskS)
vyruprocS=vyruskS/visoS*100
moteruprocS=moteruskS/visoS*100
```


Kaltininkų procentas Klaipedos mieste.

```{r}
vyruskKl<-sum(na.omit(as.numeric(Klaipedam[,19]=="Vyras")))
moteruskKl<-sum(na.omit(as.numeric(Klaipedam[,19]=="Moteris")))
visoKl<-(vyruskKl+moteruskKl)
vyruprocKl=vyruskKl/visoKl*100
moteruprocKl=moteruskKl/visoKl*100
```

Kaltininkų procentas Panevezio mieste.

```{r}
vyruskP<-sum(na.omit(as.numeric(Panevezysm[,19]=="Vyras")))
moteruskP<-sum(na.omit(as.numeric(Panevezysm[,19]=="Moteris")))
visoP<-(vyruskP+moteruskP)
vyruprocP=vyruskP/visoP*100
moteruprocP=moteruskP/visoP*100
```
